---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infraflow.co
  resources:
  - agentgroups
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infraflow.co
  resources:
  - agentgroups/finalizers
  - pipelines/finalizers
  verbs:
  - update
- apiGroups:
  - infraflow.co
  resources:
  - agentgroups/status
  - pipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - loongcollector.loong.io
  resources:
  - loongcollectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loongcollector.loong.io
  resources:
  - loongcollectors/finalizers
  verbs:
  - update
- apiGroups:
  - loongcollector.loong.io
  resources:
  - loongcollectors/status
  verbs:
  - get
  - patch
  - update
