apiVersion: apps/v1alpha1
kind: DaemonSet
metadata:
  name: loongcollector
  namespace: loongcollector-system
spec:
  selector:
    matchLabels:
      app: loongcollector
  template:
    metadata:
      labels:
        app: loongcollector
    spec:
      tolerations:
        - operator: Exists
      containers:
      - name: loongcollector
        image: sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/ilogtail:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 400m
            memory: 384Mi
        volumeMounts:
        - name: run
          mountPath: /var/run
        - name: root
          mountPropagation: HostToContainer
          readOnly: true
          mountPath: /logtail_host
        - name: checkpoint
          mountPath: /usr/local/ilogtail/checkpoint
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      volumes:
        - hostPath:
            path: /var/run
            type: Directory
          name: run
        - hostPath:
            path: /
            type: Directory
          name: root
        - hostPath:
            path: /etc/ilogtail-ilogtail-ds/checkpoint
            type: DirectoryOrCreate
          name: checkpoint