apiVersion: infraflow.co/v1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: loongcollector-operator
    app.kubernetes.io/managed-by: kustomize
  name: pipeline-sample
spec:
  # TODO(user): Add fields here
